### ISSUE TITLE
CMYK Bridge

### ISSUE THREAD

**Issue by hyraxx** [trevjonez/Pantone-Color-Book-Builder#1]
Is there a way to have this prink out the bridge guides colours with PMS number and CMYK numbers?

**Comment by trevjonez** [comment]
Im sure with some heavy modification it would be possible, although I don't think it would add any value. 
A bridge book is typically a print side by side with an actual silk screened ink. Thus we can't capture that same behavior. However if you wanted to see what the differences were of letting your printer convert cmyk vs a spot color it would capture that. In practice it would be mostly useless.

**Comment by hyraxx** [comment]
Or maybe a way to show cmyk vals next to the pms on the existing print.

**Comment by trevjonez** [comment]
Keep in mind that the generated blocks are filled with spot colors which is interpreted differently by your rip software. The swatch has a predefined color so the computer display knows how to show it (could be many different formats). The main purpose for a chart like this is to deliver perfect consistency from your design software through to the media given you follow the same process of sending from software to rip and ensure the rip config was the same for all passes.

If you were to add CMYK values to this list they would have to be calculated based a single point in that chain and thus not be accurate to the output.

Typically the rip has a spot replacement lookup table that it then adjusts based on icc profiles you can create for the particular printer/media combo. That is the key component that the rip does 100% of the adjustments based on fixed repeatable input. 

Can I ask what your workflow is? from design to rip to machine? I may be able to provide some sort of help optimizing the way you are working
